### ISSUE TITLE
Agregar informacion al usuario si su mail o password es incorrecto

### ISSUE THREAD

**Issue by emiarias** [Miltoco21/FullStack-Final#7]
al iniciar sesion si el mail o password del usuario es incorrecto se ve que no puede ingresar en consola, pero no hay ningun mensaje que le indique al usuario su error.

![image](https://user-images.githubusercontent.com/18445151/191798295-d00ef08d-e53d-46cc-85cc-46be73aeae53.png)

**Comment by Miltoco21** [comment]
Hola buen dia, quisera saber si pudieron ingresar de todas formas al resto de la pagina y saber si hay mas errores para resolver o solo seria el mensaje en cuestion? saludos

**Comment by earias08** [comment]
Hola, se puede ingresar al resto de las paginas, los errores que encontramos en otros lugares de la web estan descriptos en el resto de los issues. 
En este caso en el formulario de login como en el registro se le debe indicar al usuario si completo los datos de forma incorrecta con algun mensaje, de manera que el usuario sepa que tiene que modificar y ademas faltan las validaciones html como limitar la cantidad de caracteres que se pueden escribir en este formulario.

**Comment by emiarias** [comment]
> Hola buen dia, quisera saber si pudieron ingresar de todas formas al resto de la pagina y saber si hay mas errores para resolver o solo seria el mensaje en cuestion? saludos
 
Hola, se puede ingresar al resto de las paginas, los errores que encontramos en otros lugares de la web estan descriptos en el resto de los issues.
En este caso en el formulario de login como en el registro se le debe indicar al usuario si completo los datos de forma incorrecta con algun mensaje, de manera que el usuario sepa que tiene que modificar y ademas faltan las validaciones html como limitar la cantidad de caracteres que se pueden escribir en este formulario.
